version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_PORT: 5432
    volumes:
      - data-postgres:/var/lib/postgres/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"


volumes:
  data-postgres: